/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guardian anmelden */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Anmeldung erfolgreich */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Ungültige Zugangsdaten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/admin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin anmelden. Getrennter Endpunkt vom Guardian-Login: das ausgestellte Token wird mit einem eigenen, separaten Secret signiert und ist ausschließlich auf Admin-Routen gültig. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Anmeldung erfolgreich */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAuthResponse"];
                    };
                };
                /** @description Ungültige Zugangsdaten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guardian-Konto registrieren */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GuardianRegisterRequest"];
                };
            };
            responses: {
                /** @description Konto erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Guardian"];
                    };
                };
                /** @description Validierungsfehler (z. B. Passwort zu kurz) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description E-Mail bereits registriert */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardians/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eigenes Guardian-Profil abrufen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Guardian"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Eigenes Guardian-Konto löschen (kaskadiert auf Kinderprofile) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Eigenes Guardian-Profil aktualisieren */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GuardianUpdateRequest"];
                };
            };
            responses: {
                /** @description Aktualisiert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Guardian"];
                    };
                };
                /** @description Nicht authentifiziert */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/guardians/me/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle Kinderprofile des eingeloggten Guardians */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChildProfile"][];
                    };
                };
            };
        };
        put?: never;
        /** Neues Kinderprofil für den eingeloggten Guardian anlegen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChildProfileCreateRequest"];
                };
            };
            responses: {
                /** @description Erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChildProfile"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{childId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                childId: components["parameters"]["ChildId"];
            };
            cookie?: never;
        };
        /** Kinderprofil abrufen. Nur zugreifbar für den Guardian, dem das Kinderprofil gehört (Besitzer-Prüfung serverseitig). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    childId: components["parameters"]["ChildId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChildProfile"];
                    };
                };
                /** @description Kinderprofil gehört einem anderen Guardian */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Kinderprofil löschen (kaskadiert auf Lernfortschritt) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    childId: components["parameters"]["ChildId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Kinderprofil gehört einem anderen Guardian */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Kinderprofil aktualisieren (Nickname, Avatar, Sprache) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    childId: components["parameters"]["ChildId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChildProfileUpdateRequest"];
                };
            };
            responses: {
                /** @description Aktualisiert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChildProfile"];
                    };
                };
                /** @description Kinderprofil gehört einem anderen Guardian */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/children/{childId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                childId: components["parameters"]["ChildId"];
            };
            cookie?: never;
        };
        /** Lernfortschritt eines Kindes abrufen */
        get: {
            parameters: {
                query?: {
                    /** @description Filter nach Fortschrittsstatus (Name, z.B. "COMPLETED") */
                    status?: string;
                };
                header?: never;
                path: {
                    childId: components["parameters"]["ChildId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningProgress"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eigenes Admin-Profil abrufen. Erfordert ein Admin-Token (ausgestellt über POST /auth/admin-login); ein Guardian-Token wird hier abgelehnt. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Admin"];
                    };
                };
                /** @description Nicht authentifiziert oder falscher Token-Typ */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lernübungen auflisten */
        get: {
            parameters: {
                query?: {
                    language_id?: number;
                    exercise_type_id?: number;
                    is_active?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exercise"][];
                    };
                };
            };
        };
        put?: never;
        /** Neue Lernübung anlegen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExerciseCreateRequest"];
                };
            };
            responses: {
                /** @description Erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exercise"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        /** Einzelne Übung abrufen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: components["parameters"]["ExerciseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exercise"];
                    };
                };
                /** @description Nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Übung löschen (kaskadiert auf Tasks) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: components["parameters"]["ExerciseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Übung aktualisieren */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: components["parameters"]["ExerciseId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExerciseUpdateRequest"];
                };
            };
            responses: {
                /** @description Aktualisiert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exercise"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/exercises/{exerciseId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        /** Aufgaben einer Übung auflisten (sortiert nach position) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: components["parameters"]["ExerciseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
            };
        };
        put?: never;
        /** Neue Aufgabe zu einer Übung hinzufügen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: components["parameters"]["ExerciseId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCreateRequest"];
                };
            };
            responses: {
                /** @description Erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** Einzelne Aufgabe abrufen (inkl. zugeordneter Wörter) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDetail"];
                    };
                };
                /** @description Nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Aufgabe löschen */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Aufgabe aktualisieren */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskUpdateRequest"];
                };
            };
            responses: {
                /** @description Aktualisiert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{taskId}/words": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** Wörter einer Aufgabe auflisten (sortiert nach position) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WordTaskEntry"][];
                    };
                };
            };
        };
        put?: never;
        /** Wort einer Aufgabe zuordnen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        word_id: string;
                        position: number;
                    };
                };
            };
            responses: {
                /** @description Zuordnung erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/words/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mehrere Wörter einer Aufgabe zuordnen (bulk)
         * @description Legt bis zu 200 Wort-Zuordnungen in einem Request an. Bereits bestehende Zuordnungen (task_id + word_id) werden übersprungen (skipDuplicates), kein Fehler bei Duplikaten.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        words: {
                            /** Format: uuid */
                            word_id: string;
                            position: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Zuordnungen erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WordTaskEntry"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/words/{wordId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
                wordId: components["parameters"]["WordId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Wort-Zuordnung von einer Aufgabe entfernen */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entfernt */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Antwort einreichen und Fortschritt speichern */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitAnswerRequest"];
                };
            };
            responses: {
                /** @description Ergebnis inkl. aktualisiertem Fortschritt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningProgress"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wörter auflisten */
        get: {
            parameters: {
                query?: {
                    language_id?: number;
                    /** @description Volltextsuche auf Wort-Text */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Word"][];
                    };
                };
            };
        };
        put?: never;
        /** Neues Wort anlegen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WordCreateRequest"];
                };
            };
            responses: {
                /** @description Erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Word"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mehrere Wörter anlegen (bulk)
         * @description Legt bis zu 200 Wörter in einem Request an. Duplikate (gleicher Text + gleiche Sprache) werden übersprungen (skipDuplicates), kein Fehler bei Duplikaten.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        words: components["schemas"]["WordCreateRequest"][];
                    };
                };
            };
            responses: {
                /** @description Erstellt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Word"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/{wordId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wordId: components["parameters"]["WordId"];
            };
            cookie?: never;
        };
        /** Wort abrufen (inkl. Bild- und Audio-Referenz) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WordDetail"];
                    };
                };
                /** @description Nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Wort löschen (nur möglich, wenn in keiner Aufgabe verwendet) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Wort wird noch in mindestens einer Aufgabe verwendet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Wort aktualisieren */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WordUpdateRequest"];
                };
            };
            responses: {
                /** @description Aktualisiert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/words/{wordId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wordId: components["parameters"]["WordId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Bild für ein Wort setzen/ersetzen (1:1) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImageUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Image"];
                    };
                };
            };
        };
        post?: never;
        /** Bild eines Wortes entfernen */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/{wordId}/image/upload": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wordId: components["parameters"]["WordId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Bilddatei für ein Wort hochladen und speichern */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Bild hochgeladen und gespeichert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Image"];
                    };
                };
                /** @description Ungültiger Dateityp oder keine Datei */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Wort nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/{wordId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wordId: components["parameters"]["WordId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Audiodatei für ein Wort setzen/ersetzen (1:1) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AudioUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Audio"];
                    };
                };
            };
        };
        post?: never;
        /** Audiodatei eines Wortes entfernen */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/{wordId}/audio/upload": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wordId: components["parameters"]["WordId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Audiodatei für ein Wort hochladen und speichern */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wordId: components["parameters"]["WordId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Audio hochgeladen und gespeichert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Audio"];
                    };
                };
                /** @description Ungültiger Dateityp oder keine Datei */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Wort nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verfügbare Sprachen auflisten */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LookupItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercise-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verfügbare Übungstypen auflisten */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LookupItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verfügbare Fortschrittsstatus auflisten */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LookupItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LookupItem: {
            id?: number;
            name?: string;
        };
        GuardianRegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            access_token?: string;
            /** @example Bearer */
            token_type?: string;
            guardian?: components["schemas"]["Guardian"];
        };
        Guardian: {
            /** Format: uuid */
            guardian_id?: string;
            /** Format: email */
            email?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        GuardianUpdateRequest: {
            /** Format: email */
            email?: string;
            /** Format: password */
            password?: string;
        };
        AdminAuthResponse: {
            access_token?: string;
            /** @example Bearer */
            token_type?: string;
            admin?: components["schemas"]["Admin"];
        };
        Admin: {
            /** Format: uuid */
            admin_id?: string;
            /** Format: email */
            email?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ChildProfileCreateRequest: {
            nickname: string;
            avatar?: string;
            language_id: number;
        };
        ChildProfileUpdateRequest: {
            nickname?: string;
            avatar?: string;
            language_id?: number;
        };
        ChildProfile: {
            /** Format: uuid */
            child_id?: string;
            /** Format: uuid */
            guardian_id?: string;
            nickname?: string;
            avatar?: string;
            language_id?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ExerciseCreateRequest: {
            title: string;
            language_id: number;
            exercise_type_id: number;
            /** @default true */
            is_active: boolean;
        };
        ExerciseUpdateRequest: {
            title?: string;
            language_id?: number;
            exercise_type_id?: number;
            is_active?: boolean;
        };
        Exercise: {
            /** Format: uuid */
            exercise_id?: string;
            title?: string;
            language_id?: number;
            exercise_type_id?: number;
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TaskCreateRequest: {
            question: string;
            correct_answer: string;
            /** @default 0 */
            position: number;
        };
        TaskUpdateRequest: {
            question?: string;
            correct_answer?: string;
            position?: number;
        };
        Task: {
            /** Format: uuid */
            task_id?: string;
            /** Format: uuid */
            exercise_id?: string;
            question?: string;
            correct_answer?: string;
            position?: number;
        };
        TaskDetail: components["schemas"]["Task"] & {
            words?: components["schemas"]["WordTaskEntry"][];
        };
        WordTaskEntry: {
            word?: components["schemas"]["Word"];
            position?: number;
        };
        SubmitAnswerRequest: {
            /** Format: uuid */
            child_id: string;
            answer: string;
        };
        WordCreateRequest: {
            text: string;
            language_id: number;
        };
        WordUpdateRequest: {
            text?: string;
            language_id?: number;
        };
        Word: {
            /** Format: uuid */
            word_id?: string;
            text?: string;
            language?: components["schemas"]["LookupItem"];
        };
        WordDetail: components["schemas"]["Word"] & {
            image?: components["schemas"]["Image"];
            audio?: components["schemas"]["Audio"];
        };
        ImageUpsertRequest: {
            /** Format: uri */
            url: string;
            description?: string;
        };
        Image: {
            /** Format: uuid */
            image_id?: string;
            /** Format: uuid */
            word_id?: string;
            /** Format: uri */
            url?: string;
            description?: string;
            /** @description Dateiformat laut Cloudinary (z. B. "jpg", "png"). Null bei manuell per URL gesetzten Bildern. */
            format?: string | null;
            /** @description Dateigröße in Bytes laut Cloudinary. Null bei manuell per URL gesetzten Bildern. */
            bytes?: number | null;
        };
        AudioUpsertRequest: {
            /** Format: uri */
            url: string;
            duration_ms?: number;
        };
        Audio: {
            /** Format: uuid */
            audio_id?: string;
            /** Format: uuid */
            word_id?: string;
            /** Format: uri */
            url?: string;
            duration_ms?: number;
            /** @description Dateiformat laut Cloudinary (z. B. "mp3", "wav"). Null bei manuell per URL gesetztem Audio. */
            format?: string | null;
            /** @description Dateigröße in Bytes laut Cloudinary. Null bei manuell per URL gesetztem Audio. */
            bytes?: number | null;
        };
        LearningProgress: {
            /** Format: uuid */
            progress_id?: string;
            /** Format: uuid */
            child_id?: string;
            /** Format: uuid */
            task_id?: string;
            status?: components["schemas"]["LookupItem"];
            score?: number;
            /** Format: date-time */
            completed_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
    };
    responses: never;
    parameters: {
        ChildId: string;
        ExerciseId: string;
        TaskId: string;
        WordId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
